In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
df = pd.read_csv("Iris (1).csv")

In [6]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,4.9,3.0,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
4,NaN,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [7]:
df.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  NaN            4.7           3.2            1.3           0.2  Iris-setosa
3  NaN            4.6           3.1            1.5           0.2  Iris-setosa
4  NaN            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [9]:
gh=df.columns[1:3]

In [10]:
df[gh]

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [11]:
df.shape

(150, 6)

In [12]:
df.info

<bound method DataFrame.info of         Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1.0            5.1           3.5            1.4           0.2
1      2.0            4.9           3.0            1.4           0.2
2      NaN            4.7           3.2            1.3           0.2
3      NaN            4.6           3.1            1.5           0.2
4      NaN            5.0           3.6            1.4           0.2
..     ...            ...           ...            ...           ...
145  146.0            6.7           3.0            5.2           2.3
146  147.0            6.3           2.5            5.0           1.9
147  148.0            6.5           3.0            5.2           2.0
148  149.0            6.2           3.4            5.4           2.3
149  150.0            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [13]:
df.describe

<bound method NDFrame.describe of         Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1.0            5.1           3.5            1.4           0.2
1      2.0            4.9           3.0            1.4           0.2
2      NaN            4.7           3.2            1.3           0.2
3      NaN            4.6           3.1            1.5           0.2
4      NaN            5.0           3.6            1.4           0.2
..     ...            ...           ...            ...           ...
145  146.0            6.7           3.0            5.2           2.3
146  147.0            6.3           2.5            5.0           1.9
147  148.0            6.5           3.0            5.2           2.0
148  149.0            6.2           3.4            5.4           2.3
149  150.0            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [14]:
df.isnull().sum()

Id               6
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [15]:
df.dtypes
df['Species']=df['Species'].astype('category')

In [16]:
df.dtypes

Id                float64
SepalLengthCm     float64
SepalWidthCm      float64
PetalLengthCm     float64
PetalWidthCm      float64
Species          category
dtype: object

In [30]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [31]:
cols = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

In [32]:
df[cols] = df[cols].astype(float)

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
sc = MinMaxScaler()

In [39]:
df[cols]=sc.fit_transform(df[cols])

In [40]:
df

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1.0       0.222222      0.625000       0.067797      0.041667        0
1      2.0       0.166667      0.416667       0.067797      0.041667        0
2      NaN       0.111111      0.500000       0.050847      0.041667        0
3      NaN       0.083333      0.458333       0.084746      0.041667        0
4      NaN       0.194444      0.666667       0.067797      0.041667        0
..     ...            ...           ...            ...           ...      ...
145  146.0       0.666667      0.416667       0.711864      0.916667        2
146  147.0       0.555556      0.208333       0.677966      0.750000        2
147  148.0       0.611111      0.416667       0.711864      0.791667        2
148  149.0       0.527778      0.583333       0.745763      0.916667        2
149  150.0       0.444444      0.416667       0.694915      0.708333        2

[150 rows x 6 columns]

In [35]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le = LabelEncoder()

In [26]:
df['Species'] = le.fit_transform(df['Species'])

In [27]:
df

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1.0            5.1           3.5            1.4           0.2        0
1      2.0            4.9           3.0            1.4           0.2        0
2      NaN            4.7           3.2            1.3           0.2        0
3      NaN            4.6           3.1            1.5           0.2        0
4      NaN            5.0           3.6            1.4           0.2        0
..     ...            ...           ...            ...           ...      ...
145  146.0            6.7           3.0            5.2           2.3        2
146  147.0            6.3           2.5            5.0           1.9        2
147  148.0            6.5           3.0            5.2           2.0        2
148  149.0            6.2           3.4            5.4           2.3        2
149  150.0            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [28]:
df.tail()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145  146.0            6.7           3.0            5.2           2.3        2
146  147.0            6.3           2.5            5.0           1.9        2
147  148.0            6.5           3.0            5.2           2.0        2
148  149.0            6.2           3.4            5.4           2.3        2
149  150.0            5.9           3.0            5.1           1.8        2